version: '3'
services:
  sut:
    environment:
      NODE_ENV: development
      DEBUG: lib.*
      REDIS_HOST: redis
    build:
      context: ./
      dockerfile: ./Dockerfile.test
    command: 'npm test'
    links:
      - redis
  redis:
    image: redis:6.0-alpine
